apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: zigflow

build:
  artifacts:
    - image: zigflow
      docker:
        dockerfile: Dockerfile
        target: builder
      sync:
        manual:
          - src: "**/*.go"
            dest: /go/app
          - src: "**/*.yaml"
            dest: /go/app
          - src: "**/*.yml"
            dest: /go/app
  local:
    push: false
    useBuildkit: true

deploy:
  helm:
    releases:
      - name: zigflow
        chartPath: charts/zigflow
        namespace: zigflow
        createNamespace: true
        setValueTemplates:
          autoscaling.enabled: "{{default false .AUTOSCALING_ENABLED}}"
          autoscaling.minReplicas: "{{default 2 .AUTOSCALING_MIN_REPLICAS}}"
          autoscaling.maxReplicas: "{{default 10 .AUTOSCALING_MAX_REPLICAS}}"
          config.log-level: "{{default \"info\" .LOG_LEVEL}}"
          controller.enabled: "{{default false .CONTROLLER_ENABLED}}"
          image.repository: "{{.IMAGE_REPO_zigflow}}"
          image.tag: "{{.IMAGE_TAG_zigflow}}"
        setValues:
          image:
            pullPolicy: Never
          config:
            temporal-address: temporal.temporal.svc.cluster.local:7233 # Same as controller.connection.hostPort
          securityContext:
            readOnlyRootFilesystem: false
          tmpVolume:
            medium: ""
          controller:
            connection:
              hostPort: temporal.temporal.svc.cluster.local:7233 # Same as config.temporal-address

portForward:
  - resourceType: Service
    resourceName: temporal
    namespace: temporal
    port: 7233
    localPort: 7080
  - resourceType: Service
    resourceName: temporal
    namespace: temporal
    port: 8233
    localPort: 8080

profiles:
  - name: minikube
    activation:
      - kubeContext: minikube

  - name: local-workflow
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates/config.file
        value: "{{.WORKFLOW_FILE | default \"/go/app/workflow.example.yaml\"}}"
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates/workflow.enabled
        value: "{{.WORKFLOW_ENABLED | default false}}"

  - name: hello-world
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - examples/k8s-values.yaml
      - op: add
        path: /deploy/helm/releases/0/setFiles
        value:
          workflow.rawFile: examples/hello-world/workflow.yaml

  - name: heartbeat
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - examples/k8s-values.yaml
      - op: add
        path: /deploy/helm/releases/0/setFiles
        value:
          workflow.rawFile: examples/heartbeat/workflow.yaml
