document:
  dsl: 1.0.0
  taskQueue: zigflow
  workflowType: workflow1 # Workflow name - not registered if every top-level task is a "do"
  version: 0.0.1
  title: Multiple Workflows
  summary: Define and run multiple workflows within a single YAML file
  metadata:
    display: false
    tags:
      - multi-workflow
    activityOptions:
      startToCloseTimeout:
        minutes: 1
do:
  - workflow1:
      do:
        - wait:
            wait:
              seconds: 5
        - getUser:
            call: http
            with:
              method: get
              endpoint: ${ "https://jsonplaceholder.typicode.com/users/" + ($input.userId | tostring) }
  - workflow2:
      do:
        - wait:
            wait:
              seconds: 10
        - getUser:
            call: http
            with:
              method: get
              endpoint: ${ "https://jsonplaceholder.typicode.com/users/" + ($input.userId | tostring) }
