{{- if not .Values.controller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zigflow.fullname" . }}
  labels:
    {{- include "zigflow.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zigflow.selectorLabels" . | nindent 6 }}
  {{- include "zigflow.podTemplate" . | nindent 2 }}
 {{- end }}
