{{- if and .Values.workflow.enabled (or .Values.workflow.useInline .Values.workflow.rawFile) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.workflow.secret }}
  labels:
    {{- include "zigflow.labels" . | nindent 4 }}
data:
  {{- if .Values.workflow.rawFile }}
  workflow.yaml: {{ .Values.workflow.rawFile | b64enc | quote }}
  {{- else if .Values.workflow.useInline }}
  workflow.yaml: |
    {{ .Values.workflow.inline | toYaml | b64enc }}
  {{- end }}
{{- end }}
