document:
  dsl: 1.0.0
  taskQueue: zigflow
  workflowType: hello-world
  version: 0.0.1
  title: Hello World Encrypted External Storage
  summary: Hello world with Zigflow, but the data stored in an external service
  metadata:
    display: false
do:
  - set:
      output:
        as:
          data: ${ . }
      set:
        message: Hello from Ziggy
