/*
 * Copyright 2025 - 2026 Zigflow authors <https://github.com/zigflow/zigflow/graphs/contributors>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cmd

import (
	"encoding/json"
	"fmt"

	gh "github.com/mrsimonemms/golang-helpers"
	"github.com/rs/zerolog/log"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	zigschema "github.com/zigflow/zigflow/pkg/schema"
	"github.com/zigflow/zigflow/pkg/utils"
)

func newValidateSchemaCmd() *cobra.Command {
	var opts struct {
		OutputJSON bool
	}

	cmd := &cobra.Command{
		Use:   "schema <workflow-file> [workflow-file...]",
		Short: "Validate one or more workflow files against the current Zigflow JSON Schema",
		Long: `Validate one or more workflow files against the JSON Schema generated by this binary.

The schema is built in-memory at runtime from the same logic used to generate
the published schema artefact. Validation checks structural correctness: field
names, required properties, value formats, and mutual-exclusion constraints.

This command does not execute the workflow or connect to Temporal.

Supports workflow files written in YAML or JSON.

Multiple files can be provided in a single invocation. All files are validated
and results are reported together. The command exits non-zero if any file fails.

Use this subcommand to isolate schema issues from runtime validation failures.
To run both validations together, use the parent validate command:

  zigflow validate <workflow-file>

Arguments:
  workflow-file   One or more paths to Zigflow workflow files to validate`,
		Args: cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			sch, err := zigschema.CompileSchema(Version)
			if err != nil {
				return gh.FatalError{
					Cause: err,
					Msg:   "Failed to build schema",
				}
			}

			results := make([]utils.ValidationResult, 0, len(args))

			for _, filePath := range args {
				if !opts.OutputJSON {
					_, _ = fmt.Fprintf(cmd.OutOrStdout(), "Validating %s...\n", filePath)
				}

				results = append(results, buildSchemaResultFromSchema(sch, filePath))
			}

			if opts.OutputJSON {
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				_ = enc.Encode(results)
			} else {
				for _, r := range results {
					utils.RenderHuman(cmd.OutOrStdout(), r)
				}
			}

			failed := countFailed(results)

			if !opts.OutputJSON {
				_, _ = fmt.Fprintln(cmd.OutOrStdout())

				if failed == 0 {
					_, _ = fmt.Fprintf(cmd.OutOrStdout(),
						"All %d file(s) passed schema validation.\n", len(results))
				} else {
					_, _ = fmt.Fprintf(cmd.OutOrStdout(),
						"%d of %d file(s) failed schema validation.\n", failed, len(results))
				}
			}

			if failed > 0 {
				return gh.FatalError{
					Msg:    "Schema validation failed",
					Logger: log.Trace,
				}
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(
		&opts.OutputJSON, "output-json",
		viper.GetBool("output_json"), "Output as JSON",
	)

	return cmd
}

// countFailed returns the number of ValidationResults where Valid is false.
func countFailed(results []utils.ValidationResult) int {
	n := 0
	for _, r := range results {
		if !r.Valid {
			n++
		}
	}
	return n
}
