/*
 * Copyright 2025 - 2026 Zigflow authors <https://github.com/zigflow/zigflow/graphs/contributors>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cmd

import (
	"errors"

	gh "github.com/mrsimonemms/golang-helpers"
	"github.com/rs/zerolog/log"
	"github.com/santhosh-tekuri/jsonschema/v5"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	zigschema "github.com/zigflow/zigflow/pkg/schema"
	"github.com/zigflow/zigflow/pkg/utils"
)

func newValidateSchemaCmd() *cobra.Command {
	var opts struct {
		OutputJSON bool
	}

	cmd := &cobra.Command{
		Use:   "schema <workflow-file>",
		Short: "Validate a workflow file against the current Zigflow JSON Schema",
		Long: `Validate a workflow file against the JSON Schema generated by this binary.

The schema is built in-memory at runtime from the same logic used to generate
the published schema artefact. Validation checks structural correctness: field
names, required properties, value formats, and mutual-exclusion constraints.

This command does not execute the workflow or connect to Temporal.

Supports workflow files written in YAML or JSON.

The command exits with a non-zero status code if validation fails, making it
suitable for use in pre-commit hooks, CI pipelines, and local development.

Arguments:
  workflow-file   Path to the Zigflow workflow file to validate`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			filePath := args[0]
			result := utils.ValidationResult{
				File: filePath,
			}

			sch, err := zigschema.CompileSchema(Version)
			if err != nil {
				return gh.FatalError{
					Cause: err,
					Msg:   "Failed to build schema",
				}
			}

			if err := zigschema.ValidateFile(sch, filePath); err != nil {
				var ve *jsonschema.ValidationError
				if errors.As(err, &ve) {
					for _, e := range ve.BasicOutput().Errors {
						loc := e.InstanceLocation
						if loc == "" {
							loc = "(root)"
						}

						result.Errors = append(result.Errors, utils.ValidationErrors{
							Path:    loc,
							Message: e.Error,
						})
					}
				} else {
					result.Errors = append(result.Errors, utils.ValidationErrors{
						Path:    "(root)",
						Message: err.Error(),
					})
				}
			} else {
				result.Valid = true
			}

			if opts.OutputJSON {
				_ = utils.RenderJSON(cmd.OutOrStdout(), result)
			} else {
				utils.RenderHuman(cmd.OutOrStdout(), result)
			}

			if !result.Valid {
				return gh.FatalError{
					Msg:    "Schema validation failed",
					Logger: log.Trace,
				}
			}

			return nil
		},
	}

	cmd.Flags().BoolVar(
		&opts.OutputJSON, "output-json",
		viper.GetBool("output_json"), "Output as JSON",
	)

	return cmd
}
