document:
  dsl: 1.0.0
  taskQueue: zigflow
  workflowType: external-calls
  version: 0.0.1
  title: External Calls
  summary: An example of how to use Zigflow to make external gRPC and HTTP calls
  metadata:
    tags:
      - http
      - grpc
use:
  authentications:
    basic_auth:
      basic:
        username: ${ $env.EXAMPLE_USERNAME }
        password: ${ $env.EXAMPLE_PASSWORD }
do:
  - fork:
      fork:
        compete: false
        branches:
          - grpc:
              call: grpc
              with:
                proto:
                  endpoint: file:///go/app/examples/external-calls/grpc/basic/proto/basic/v1/basic.proto
                service:
                  name: providers.v1.BasicService
                  host: grpc
                  port: 3000
                method: Command1
                arguments:
                  input: ${ $env.GRPC_INPUT }
          - http:
              call: http
              with:
                  method: get
                  endpoint:
                    uri: https://jsonplaceholder.typicode.com/users/3
          - http_basic:
              call: http
              with:
                  method: get
                  endpoint:
                    uri: http://server:3000/basic
                    authentication:
                      use: basic_auth
