document:
  dsl: 1.0.0
  taskQueue: zigflow
  workflowType: updates
  version: 0.0.1
  title: Update Listeners
  summary: Listen for Temporal update events
do:
  - callDoctor:
      metadata:
        timeout: 10s # Controls the AwaitWithTimeout timeout - defaults to 60s
      listen:
        to:
          # Only progress after every update received
          all:
            - with:
                # ID maps to the update name in Temporal
                id: temperature
                # Temporal update - used to make read/write request
                type: update
                acceptIf: ${ $data.temperature > 38 }
            - with:
                id: bpm
                type: update
                acceptIf: ${ $data.bpm < 60 or $data.bpm > 100 }
  - wait:
      output:
        as:
          temperature: ${ $data.temperature }
          bpm: ${ $data.bpm }
      wait:
        seconds: 10
